### ISSUE TITLE
USER STORY: 0.2 - database schema

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#2]
As a **developer**, I want to **design the database schema and define the necessary models** to **store user information, travel memories, and other relevant data.**

# Acceptance Cirteria: 
* Acceptance Criteria 1: The database schema is designed to efficiently store and retrieve data.
* Acceptance Criteria 2: Models are defined for travelers, followers, likes, memories(posts) and any additional entities required.

# Tasks
- [ ] Analyze the data requirements and relationships within the platform.
- [ ] Design the database schema 
- [ ] Create a new database in ElephantSQL
- [ ] Define models in the backend framework ( Django) based on the database schema
