### ISSUE TITLE
USER STORY: View Comments

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#22]
As a user, I can view and read comments on posts on the Travel Tickr platform, so that I can follow the conversations and opinions shared by other users.

# Acceptance Cirteria: 
* Acceptance Criteria 1: Comments should be displayed in a visually appealing and organized manner, making it easy to read and follow the conversations.

# Tasks
- [x] Design and implement the UI component to display comments.
- [x] Fetch and retrieve comments associated with each post from the backend.
- [ ] Implement infinitive scrolling on comments
