### ISSUE TITLE
USER STORY: Update Comment

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#23]
As a user, I can update my own comments on the Travel Tickr platform, so that I can make edits or corrections to my shared opinions.

# Acceptance Criteria: 
* Acceptance Criteria 1: Visible edit button on owners comments

# Tasks
- [ ] Add an edit button/icon next to the user's own comments.
- [ ] Implement functionality to allow users to edit their comments.
- [ ] Update the comment in the backend database when changes are saved.
