### ISSUE TITLE
USER STORY: Delete Comment

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#24]
As a user, I can delete my own comments on the Travel Tickr platform, so that I can remove or retract my previous statements.

# Acceptance Cirteria: 
* Acceptance Criteria 1: Visible button to delete users own comment.

# Tasks
- [x] Add a delete button/icon on the user's own comments.
- [x] Implement functionality to allow users to delete their comments.
- [x] Remove the comment from the backend database when it is deleted.
