### ISSUE TITLE
USER STORY: Follow users

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#25]
As a user, I can follow other users on the Travel Tickr platform, so that I can stay updated on their travel journeys and experiences.

# Acceptance Cirteria: 
* Acceptance Criteria 1: Users should be able to follow other users.
* Acceptance Criteria 2: The followed user's updates and posts should be visible to the follower in their feed
* Acceptance Criteria 3: The followed users number of followers will increase with one.

# Tasks
- [x] Add a follow button/icon on user profiles and/or posts.
- [x] Implement functionality to allow users to follow other users.
- [x] Implement functionality to increase the number of following for the user that is following the other user
- [x] Implement functionality to increase the number of followers for a user when they are followed by another user.
- [x] Implement the function and button to also unfollow a user
