### ISSUE TITLE
USER STORY: Maintain user environment

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#26]
As a site owner, I can delete user accounts, posts, and comments on the Travel Tickr platform, so that I can maintain a safe and high-quality user environment.

# Acceptance Cirteria: 
* Acceptance Criteria 1: Site owner can delete user accounts, posts and comments that are not appropriate

# Tasks
- [x] Implement functionality for site owner to delete user accounts.
- [x] Implement functionality for site owner to delete posts.
- [x] Implement functionality for site owner to delete comments.
