### ISSUE TITLE
USER STORY: 0.3 - set up the project repository and version control system

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#3]
As a developer, I want to set up the project repository and version control system to facilitate code management.

# Acceptance Cirteria: 
* Acceptance Criteria 1: The project repository is created with the necessary structure and files.
* Acceptance Criteria 2: A version control system (Git) is configured to manage code changes.

# Tasks
- [ ] Create a project repository on Github.
- [ ] Set up the repository structure with directories for backend code, documentation, planning and other relevant files.
- [ ] Configure the version control system to track changes.
