### ISSUE TITLE
USER STORY: Location

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#36]
As a **user** I can **see a posts location** so that **I can  know where the memory was made**

# Acceptance Cirteria: 
* Acceptance Criteria 1: Post app is updated with model for location
* Acceptance Criteria 2: Location is visible on every post.

# Tasks
- [x] Create a location model with a Foreign Key relationship to the post model
- [ ] Create a migration for the changes
- [ ] Update database schema
- [ ] Update the post view to show location

**Comment by SandraBergstrom** [comment]
I had issues when implementing this to the PostCreateForm since it didn't want to post to 2 different API-endpoints. Because of this I made a desicion that it would save me time to instead update the Post model to include name location and contry.
