### ISSUE TITLE
USER STORY: Popular travelers

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#50]
As a **user** I can **see which the most popular travelers are** so that **I can get inspired by them**

# Acceptance Cirteria: 
* Acceptance Criteria 1: The most popular travelers are presented in a visually appealing and clear manner.
* Acceptance Criteria 2: I can click on a traveler to access more information about the person and view their content.

# Tasks
- [x] Create a functionality to retrieve and display information about the travelers, including their profiles and content.
- [x] Design and implement a visually pleasing layout to showcase the most popular travelers.
- [x] Implement a feature that allows users to click on a traveler to view more detailed information and explore their content.
- [x] Add a button to quickly follow the popular user
