### ISSUE TITLE
USER STORY: Like comments

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#54]
As a **user** I can **like comments** so that **I can express my agreement or support for a comment**

# Acceptance Cirteria: 
* Acceptance Criteria 1: User is able to see a 'like' button or icon.
* Acceptance Criteria 2:  When a user clicks the 'like' button the number of likes increments. 
* Acceptance Criteria 3: User can not like more than once.

# Tasks
- [x] Update the like model and related backend code to suppoort likes on comments
- [x] Update the frontend Comment component to include a 'like' button and display the number of likes a comment has. 
- [x] Add code on the frontend to handle 'like' button clicks
