### ISSUE TITLE
USER STORY: Improve application and deployment

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#57]
As the **owner** of the application, I want to **improve the application's codebase and deployment process** to **ensure efficiency and maintainability**.

# Acceptance Cirteria: 
* Acceptance Criteria 1: Improve the codebase by removing strictMode, organizing imports, and removing console logs.
* Acceptance Criteria 2: Streamline the deployment process by adding Heroku-specific deployment commands.

# Tasks
- [x] Remove strictMode
- [x] Add functions in utils to set, refresh and remove TokenTimestamp. Then add the functions to currentUserContext, LoginForm and Navbar.
- [x] Adjust and organise your imports to minimise the build
- [x] Remove all the console.logs from the application
- [x] Replace the application default title in index.html
- [x] Refetch posts when the currentUser changes
- [x] Add the heroku deployment commands
