### ISSUE TITLE
USER STORY: 404-page

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#58]
As an **owner,** I want to c**reate a 404 page to improve the user experience** **when users land on non-existent pages.**

# Acceptance Cirteria: 
* Acceptance Criteria 1: The 404 page should be visually appealing and user-friendly.

# Tasks
- [x] Design and implement the layout of the 404 page.
- [x] Add relevant error message and instructions to the 404 page.
- [x] Style the 404 page to match the overall theme and branding of the website.
- [x] Test to see if the 404 page is showing as it should be
