### ISSUE TITLE
USER STORY: 0.6

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#6]
As a developer, I want to create API endpoints to handle user registration, login, and profile management.

# Acceptance Cirteria: 
* Acceptance Criteria 1: API endpoints are created for user registration, login, and profile management.
* Acceptance Criteria 2: 
* Acceptance Criteria 3:

# Tasks
- [ ] Define API endpoints for user registration, login, and profile management.
- [ ] Implement the necessary backend logic to handle requests to these endpoints.
- [ ] Test the API endpoints
