### ISSUE TITLE
USER STORY: About page

### ISSUE THREAD

**Issue by SandraBergstrom** [SandraBergstrom/travel-tickr#61]
As a **user** I can **view the about page** so that **I can gain information about Travel Tickr**

# Acceptance Cirteria: 
* Acceptance Criteria 1: Visible link in navbar to About page
* Acceptance Criteria 2: The page should provide a brief description of Travel Tickr.
* Acceptance Criteria 3:

# Tasks
- [x] Create the about page component
- [x] Add the content
- [x] Add it to the routes in app.js
- [x] Add the page to the navbar
